---
title: "Happiness and the evolution of brain size"
description: |
  What are the mecanics of brain evolution ?.
author:
  - name: Senghor Kahungu Pombo
date: "`r Sys.Date()`"
categories:
  - "English for Science"
#preview:
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Source of the article with publication date and word count:
Source of the article: https://www.sciencedaily.com/releases/2020/10/201023123137.htm 

October 23/2020

Word count: 598

# VOCABULARY:
| Word from the text |                                                                                    Synonym/definition in English                                                                                   | French translation |
|--------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|--------------------|
| Stem cell          | self-renewing cell /a cell that upon division replaces its own numbers and also gives rise to cells that differentiate further into one or more specialized types, as various B cells and T cells. | Cellule souche     |
| fetal              | of, relating to, or having the character of a fetus:                                                                                                                                               | foetal             |

# ANALYSIS TABLE ABOUT THE STUDY:
|  			Researchers?  			 		                       |  			Researchers 			at the Max Planck Institute of Molecular Cell Biology and Genetics 			in Dresden, together with colleagues at the University Hospital 			Carl Gustav Carus Dresden.  			   			  			  			The 			postdoctoral researcher Lei Xing in the Huttner group.  			   			 		                                                                                                                                                                                                                       |
|----------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  			Published in? when (if 			mentioned)?  			 		 |  			Science 			daily (10/23/2020) 		                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|  			General topic  			 		                      |  			The 			role of the neurotransmitter serotonin in the brain evolution. 		                                                                                                                                                                                                                                                                                                                                                                                                      |
|  			Procedure/ what was examined  			 		       |  			Researchers 			exploited datasets generated by the group in the past and found 			that the serotonin receptor HTR2A was expressed in fetal human, 			but not embryonic mouse, neocortex. To explore this, the 			researchers induced the production of the HTR2A receptor in 			embryonic mouse neocortex. They have found that serotonin, by 			activating this receptor, caused a chain of reactions that 			resulted in the production of more basal progenitors in the 			developing brain. 		 |
|  			Conclusions/ discovery  			 		             |  			Serotonin 			can act as a growth factor for the stem 			cells in the fetal 			human brain that determine brain size. 		                                                                                                                                                                                                                                                                                                                                                             |
|  			Remaining questions  			 		                |  			/ 		                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |

